### ISSUE TITLE
BCP212

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/smart-app-launch#292]
IETF now has Best Current Practice 212 (BCP212) for use of OAuth 2 with native apps. There surely is some, or all of it that should be recommended to the SMART community.
https://tools.ietf.org/html/bcp212

**Comment by isaacvetter** [comment]
One notable recommendation from IETF:

>7.2.  Claimed "https" Scheme URI Redirection
>App-claimed "https" scheme redirect URIs have some advantages
   compared to other native app redirect options in that the identity of
   the destination app is guaranteed to the authorization server by the
   operating system.  For this reason, native apps SHOULD use them over
   the other options where possible

https://tools.ietf.org/html/bcp212#section-7.2

These "claimed https urls" are variously named:
-  [Windows "app URI handlers"](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking)
- [Android app links](https://developer.android.com/training/app-links/) 
- [iOS Universal Links](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html). 

They all work in the same way and allow a desktop/mobile app to be associated with a regular https url, such that when the registered url is navigated to, the app opens instead of a browser.

Also:

>6.  Initiating the Authorization Request from a Native App
>Public native app clients MUST implement the Proof Key for Code
   Exchange (PKCE [RFC7636]) extension to OAuth, and authorization
   servers MUST support PKCE for such clients, for the reasons detailed
   in Section 8.1.

https://tools.ietf.org/html/bcp212#section-6

**Comment by spalte** [comment]
The current [document](http://www.hl7.org/fhir/smart-app-launch/#step-3-app-exchanges-authorization-code-for-access-token) states that:

> For public apps, authentication is not possible (and thus not required), since a client with no secret cannot prove its identity when it issues a call. (The end-to-end system can still be secure because the client comes from a known, https protected endpoint specified and enforced by the redirect uri.) 

This is not true. The Authorization Code is sent as a query parameter to the `redirect_uri`. While the query parameters were encrypted using TLS, it is likely that the Authorization Code will be leaked by system (browser history or server logging for example) since the URL is usually not considered protected content. If the Authorization Code is leaked, it can be used to hijack the session. This is the reason [PKCE](https://tools.ietf.org/html/rfc7636) was designed, and it definitely should be used in a healthcare context where many individuals will likely have access to the same computer, use the same browser, and will have access to the browser history.

**Comment by jmandel** [comment]
We have adopted PKCE in the latest release of SMART.
