### ISSUE TITLE
simple, PKCE support

### ISSUE THREAD

**Issue by isaacvetter** [HL7/smart-app-launch#313]
It would be good to describe a simple, optional PKCE profile as part of this revision to SMART app launch. 

Perhaps something like (very rough):

Proof Key for Code Exchange (PKCE): This is a standardized, cross-platform technique for public clients to mitigate the threat of authorization code interception. However, it requires additional support from the authorization server and app. PKCE is described in IETF RFC 7636. SMART requires the S256 code_challenge_method. The "plain" method is not supported.

## authorization step
code_challenge: This optional parameter is generated by your app and used for PKCE. This is the S256 hashed version of the code_verifier parameter, which will be used in the token request.
code_challenge_method: This optional parameter indicates the method used for the code_challenge parameter and is required if using that parameter. S256 method 

## token request
code_verifier: This optional parameter is used to verify against your code_challenge parameter when using PKCE. This parameter is passed as free text and must match the code_challenge parameter used in your authorization request once it is hashed on the server using the code_challenge_method.

**Comment by jmandel** [comment]
Do you have a proposed level of conformance requirements here? Would it be optional for servers to support, and optional for apps to opt into?

(In general, there are some risks that PKCE can mitigate, but they don't include all scenarios where an authorization code might be interrupted. App-claimed URLs can mitigate some of these cases too.)

**Comment by isaacvetter** [comment]
Hey Josh,

re: conformance requirements. A few thoughts:
1) I _think_ that any AS permitting the registration of a non-https redirect_uri may be insecure without the use of PKCE. So one option would be for AS to SHALL not permit non-https redirect uris during registration unless the AS permits the app to use PKCE. So, optional for apps, unless the app uses non-https redirect uris and optional for AS, unless they permit the registration of non-https redirect uris. This would work well for manual registration, but could be improved with some form of discovery for any future use of dynreg.
2) While #1 is more technically correct, a simpler approach would be updating ./well-known/smart-configuration to enable an AS to advertise it's support for PKCE, and making support optional for both the AS and the app.

What do you think?

Isaac

**Comment by jmandel** [comment]
Re: discovery, adding `code_challenge_methods_supported` to our `.well-known/smart-configuration` file would be an easy thing to do, following the definitions at https://tools.ietf.org/html/rfc8414 -- I think we should do this regardless of whether we decide to make PKCE support a requirement, because discovering *which* challenges methods are supported is important too.

Re (1), when you write "non-https", just to check -- here you're really to non-network URL schemes (e.g., a "custom URL scheme" like `myapp://` or a local value like `http://localhost:8000`? Because we already say:

> Apps SHALL ensure that sensitive information (authentication secrets, authorization codes, tokens) is transmitted ONLY to authenticated servers, over TLS-secured channels

... which precludes non-HTTPS *network* URLs.

My take on conformance would be: if we can get agreement that servers `SHALL` support PKCE, and `SHALL NOT` require it for `https` URLs, that'd be a win.

**Comment by isaacvetter** [comment]
> Re (1), when you write "non-https", just to check -- here you're really to non-network URL schemes

Yes, exactly. 

Perhaps a good discussion topic for tomorrow would be polling the community of EHRs to determine the appropriate level of conformance?
